### ISSUE TITLE
Vertical scroll speed too fast (xrdpMouse)

### ISSUE THREAD

**Issue by fabwu** [neutrinolabs/xorgxrdp#150]
I'm using xrdp with Hyper-V to run Ubuntu 18.04 in a VM and the vertical scroll speed of the mouse is too fast. 

I couldn't find any options in the xrdpMouse driver so I wanted to asked you if it is possible to adjust the scroll sensitivity?

**Comment by bmcmullin** [comment]
Same issue, but on Linux Mint xfce 19.3 (layered on Ununtu 18.04 anyway). Quite frustrating, as the VM is otherwise _almost_ fully usable for everyday work, but this is sadly very close to a showstopper. Current workaround is just ignore touchpad and plug in a USB mouse but would be much nicer if touchpad _could_ be properly configured. 

FWIW: I did find [this discussion of installing xserver-xorg-input-synaptics-hwe-18.04](https://askubuntu.com/questions/1031940/how-to-switch-from-libinput-to-synaptics-in-ubuntu-18-04/1103903#1103903) (also [mentioned in the Mint 19.3 release notes](https://linuxmint.com/rel_tricia_cinnamon.php)); but that driver doesn't seem to load under xrdp - I assume because in that case, it the VM lacks direct hardware access to recognise/identify the touchpad). So we need something that "native" to xrdp?

**Comment by Marchen** [comment]
Same issue, on Ubuntu 18.04 connecting from MacOS.

**Comment by dblaber** [comment]
I am also having this issue, macbook pro, tigervnc viewer+server works fine, but xrdp + xorgxrdp and xrdp+Xvnc scroll too fast, almost unusable mouse scrolling.  Anyone have any work around?

**Comment by bmcmullin** [comment]
Only workaround for the moment seems to be to use an external mouse in place of the trackpad...

**Comment by dblaber** [comment]
@bmcmullin Do you also have a mac trackpad? 

I am thinking this is an xrdp issue, not an xorgxrdp issue, as Xvnc +xrdp also has same issue. Doesn't Xvnc use its own virtual devices?

**Comment by bmcmullin** [comment]
"Do I have a mac trackpad?" - No: currently working on PC laptop hardware only - so can't personally vouch for this as a workaround on Mac or anything else. Would be useful to have a report on that of course.

**Comment by elixd** [comment]
Same using macOS trackpad. Scrolling is too fast to the point of being unusable

**Comment by rbreaves** [comment]
This does need addressing - finding a way to adjust the scroll speed of an xrdpmouse is important.

**Comment by jituce** [comment]
same issue with linux mint , any one got any solution yet?

**Comment by pauloabeck** [comment]
Same issue with xfce4, Ubuntu 20.04, RDP. Tweaking mouse properties does not help.

**Comment by metalefty** [comment]
I confirmed it is actually an issue. It needs to be addressed.

**Comment by ivhacks** [comment]
Same issue here, Dell Precision 7760/Windows 10 Host, Ubuntu 20.04 Guest.

**Comment by abulujayn** [comment]
Would love to see this fixed. I'd attempt it myself but I don't even know where to start; if someone could offer some guidance, I could try to get something going.

**Comment by andro42** [comment]
Using MS RDP Client  to connect to Linux Mint machine (xRDP). I have same problem. Anybody found any workaround?

**Comment by rbreaves** [comment]
Use ssh and x11vnc?

**Comment by chrisbitmead** [comment]
Personally I don't consider vnc a solution because it sucks so much with multiple monitors, whereas rdp is fantastic with multiple monitors.

**Comment by andro42** [comment]
> Personally I don't consider vnc a solution because it sucks so much with multiple monitors, whereas rdp is fantastic with multiple monitors.

I agree.

I was testing it with "xinput test <id>". And got "Pressed Button 5" or "Pressed Button 4" when scrolling with 2 finger on touchpad (Synaptics). The same happens when using hardware mouse wheel, but this is more controllable compared to touchpad. Did not found any setting to change this behavior.

**Comment by rbreaves** [comment]
> Personally I don't consider vnc a solution because it sucks so much with multiple monitors, whereas rdp is fantastic with multiple monitors.

Why I use separate user sessions.. and a terminal that can access a shared tmux session. And that is whether I use RDP or VNC.. currently I use both, and I do not mean layered inside of xrdp. I straight up use vnc over ssh on Linux and rdp from Windows.

There are other good and valid reasons to break up things even with 2 separate rdp sessions imho. Virtual desktops can then be per monitor instead of workspace.. which is annoying.

**Comment by seflerZ** [comment]
This is because xrdp doesn't have a touchpad driver and simulate the touchpad as mouse. In the xorgxrdp source code there're only mouse and keyborad event. When scrolling in touchpad, xrdp translate the event as mouse scrolling which will be too many (because touchpad is continous scrolling).

```
sefler@ubuntu:~$ xinput --list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ xrdpMouse                               	id=6	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ xrdpKeyboard                            	id=7	[slave  keyboard (3)]
```

According to Xorg documentation, touchpad event should be triggered by method called "xf86PostTouchEvent()", but currently xorgxrdp lib has only "xf86PostButtonEvent".

A hack solution would be adding a threshold in wheel scroll event which event_msg_ids are 107,108(UP) 109,110(DOWN). The threshold can be placed in "rdpInput.c" like:
```
int
rdpInputMouseEvent(rdpPtr dev, int msg,
                   long param1, long param2,
                   long param3, long param4)
{
    dev->last_event_time_ms = GetTimeInMillis();
    + if (msg == 108 || msg == 110 || msg == 107 || msg == 109) {
    +   if (dev->last_event_time_ms - dev->last_wheel_time_ms < 50)
    +    {
    +       return 0;
    +    }
    + }

    + if (msg == 107 || msg == 109) {
    +   dev->last_wheel_time_ms = dev->last_event_time_ms;
    + }

    if (g_input_proc[1].proc != 0)
    {
        return g_input_proc[1].proc(dev, msg, param1, param2, param3, param4);
    }
    return 0;
}
``` 
I've compiled it and tested to be okay.

**Comment by metalefty** [comment]
@seflerZ Thanks for the help!

**Comment by Bappy1988** [comment]
I wonder if this fix could be plugged into the main driver branch under a toggle called "slow down touchpad scrolling" ? It's a tricky one because you'd probably have to manually select it on and off depending on whether you've plugged in an external mouse or not as under xrdp the input hardware is abstracted by the host device.

**Comment by realgreef** [comment]
The fixed worked for me, **but**, I had to declare _last_wheel_time_ms_ in rdp.h.
Running Slackware 15.0 and XFCE. xrdp 0.9.12, xorgxrdp 0.2.12.

```
    CARD32 last_event_time_ms;
+   CARD32 last_wheel_time_ms;

    int conNumber;
```

**Comment by seflerZ** [comment]
> I wonder if this fix could be plugged into the main driver branch under a toggle called "slow down touchpad scrolling" ? It's a tricky one because you'd probably have to manually select it on and off depending on whether you've plugged in an external mouse or not as under xrdp the input hardware is abstracted by the host device.

This is a hack solution and will not merge into the master. The best way is adding a touchpad driver and call the touchpad functions. I'll do some research when I got time.

**Comment by metalefty** [comment]
@seflerZ I'm working on merging your workaround until we get the best fix because your fix actually works and is effective. Thank you for your work. I'd appreciate it if you could keep researching.

**Comment by metalefty** [comment]
Hello everyone, I've release xorgxrdp v0.9.19 that includes a workaround to mitigate too fast scroll. 
* https://github.com/neutrinolabs/xorgxrdp/releases/tag/v0.9.19

This workaround is provided by @seflerZ and as he says, this is a hack solution but useful to mitigate too fast scroll.

Thanks @seflerZ !

**Comment by seflerZ** [comment]
@metalefty It's my pleasure. I'm intended to implement fully inertial scrolling and did make some progress. Later I'll share it.

**Comment by zobi** [comment]
> Hello everyone, I've release xorgxrdp v0.9.19 that includes a workaround to mitigate too fast scroll.
> 
> * https://github.com/neutrinolabs/xorgxrdp/releases/tag/v0.9.19
> 
> This workaround is provided by @seflerZ and as he says, this is a hack solution but useful to mitigate too fast scroll.
> 
> Thanks @seflerZ !

Hello i use xrdp 0.9.21.1 and i still have the same issue with macbookair connect with xrdp to a kali vm.
I try : 
`XRDP_XORG_TOUCHPAD_SCROLL_HACK=yes` in `sesman.ini` 
But it didn't work for me ... 
Have you an idea ? 
Thanks a lot

**Comment by seflerZ** [comment]
It may be caused by Mac Touchpad sends more events than ordinary touch pad.You can use the latest working branch. It contains a complete solution. Just download and compile it.-------- 原始邮件 --------发件人： Zobi ***@***.***>日期： 2023年7月28日周五 17:39收件人： neutrinolabs/xorgxrdp ***@***.***>抄送： Sefler Zhou ***@***.***>, Mention ***@***.***>主    题： Re: [neutrinolabs/xorgxrdp] Vertical scroll speed too fast (xrdpMouse) (#150)

Hello everyone, I've release xorgxrdp v0.9.19 that includes a workaround to mitigate too fast scroll.
https://github.com/neutrinolabs/xorgxrdp/releases/tag/v0.9.19
This workaround is provided by @seflerZ and as he says, this is a hack solution but useful to mitigate too fast scroll.
Thanks @seflerZ !

Hello i use xrdp 0.9.21.1 and i still have the same issue with macbookair connect with xrdp to a kali vm.
I try :
XRDP_XORG_TOUCHPAD_SCROLL_HACK=yes in sesman.ini
But it didn't work for me ...
Have you an idea ?
Thanks a lot

**Comment by furrnace** [comment]
I have vertical scrolling issues (too fast) on macOS RDP with these packages on Debian bookworm:

Package: xorgxrdp
Version: 1:0.9.19-1

Package: xrdp
Version: 0.9.21.1-1

Package: xorg
Version: 1:7.7+23

/etc/xrdp/sesman.ini:
```
[SessionVariables]
PULSE_SCRIPT=/etc/xrdp/pulse/default.pa
XRDP_XORG_TOUCHPAD_SCROLL_HACK=yes

```

This should in theory work fine with the above versions?

**Comment by metalefty** [comment]
Sudddenly 3 people @dropwhile @zobi @furrnace has reported `XRDP_XORG_TOUCHPAD_SCROLL_HACK=yes` is not  wokring with macOS RDP in a month.

I certainly confirmed the fix mitigates too fast scroll speed before making a release. It is definitely a working mitigation a year ago. So I guess something has changed in macOS RDP client and it disables the mitigation.
