### ISSUE TITLE
CentOS8 dependencies name

### ISSUE THREAD

**Issue by sg4r** [neutrinolabs/xorgxrdp#173]
xorgxrdp dependencis error name. the package search xorg-x11-server-Xorg(x86-64) = 1.20.6 and must xorg-x11-server-Xorg=>1.20.6

# yum install xorgxrdp
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:06:15 ago on Mon Nov 30 09:43:27 2020.
Error: 
 Problem: conflicting requests
  - nothing provides xorg-x11-server-Xorg(x86-64) = 1.20.6 needed by xorgxrdp-0.2.14-2.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
# yum info xorg-x11-server-Xorg
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:06:28 ago on Mon Nov 30 09:43:27 2020.
Installed Packages
Name         : xorg-x11-server-Xorg
Version      : 1.20.8
Release      : 6.el8
Architecture : x86_64
Size         : 3.7 M
Source       : xorg-x11-server-1.20.8-6.el8.src.rpm
Repository   : @System
From repo    : CentOS-8-AppStream
Summary      : Xorg X server
URL          : http://www.x.org
License      : MIT
Description  : X.org X11 is an open source implementation of the X Window System.  It
             : provides the basic low level functionality which full fledged
             : graphical user interfaces (GUIs) such as GNOME and KDE are designed
             : upon.

**Comment by matt335672** [comment]
Hi @sg4r 

You're quite right in that for some reason xorgxrdp hasn't been rebuilt for CentOS 8 - see https://koji.fedoraproject.org/koji/packageinfo?packageID=23887. It's been rebuilt for Fedora 32-34 though, so this is probably an oversight.

**We don't provide the packaging for xorgxrdp on CentOS** - this is done by the EPEL project which is part of Fedora.

According to [this web page](https://fedoraproject.org/wiki/EPEL), you'll need to raise this a bugzilla on this at https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora+EPEL

Possible workarounds in the meantime:-
- Use the Xvnc backend instead of Xorg if this suits your workflow.
- Try installing the Fedora 32 package manually with `dnf install` if you download it from a mirror (for example https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/fedora/linux/updates/32/Everything/x86_64/Packages/x/xorgxrdp-0.2.14-3.fc32.x86_64.rpm. This may work.

I'm closing this one, as it's out of our scope. I hope the above info is useful.
