### ISSUE TITLE
Can xrdp + xorgxrdp be used to share the current local session (like x11vnc port 5900 + xrdp)

### ISSUE THREAD

**Issue by zilexa** [neutrinolabs/xorgxrdp#190]
On Ubuntu 20.10 I have disabled the built in desktop share (uses vino) and installed x11vnc. 
My xrdp.ini has: 
```
[vnc-any]
name=vnc-any
lib=libvnc.so
ip=127.0.0.1
port=5900
username=
password=ask
xserverbpp=24
```
This way, when I connect, it asks for a password that is defined in my x11vnc systemd service file and then I see the current, local desktop session. 

Can this also be done without vnc? I have xorgrdp installed but unclear what the session should look like in the .ini file. The key element to share the local desktop session via vnc was the port number 5900. 

I tried adding this, but not sure where to set a password, so I left that empty just to test:
```
[xorgrdp]
name=xorgrdp
lib=libxup.so
ip=127.0.0.1
port=3389
username=
password=
xserverbpp=24
code=20
```

When I try to connect, I just get a message (connecting via Apache Guacamole) You have been disconnected.

**Comment by RavenWing71** [comment]
VNC is a precursor to RemoteDesktop designed by AT&T back in the Windows 3.1 days.  With a VNC client on your workstation, you should be able to connect directly to x11vnc without the RDP protocol.  When you use x11vnc as a middleman for Xrdp, Xrdp has to know which port on localhost to connect to for it to talk to x11vnc as if it were a VNC client.  Port 5900 is the default for VNC.
XorgXrdp instead is a set of drivers for Xorg X11 to allow Xrdp to look like a Keyboard, Mouse and Monitor(s) to the X11 windowing system.  No port number is needed.
Could XorgXrdp allow you to connect to an existing X11 session?  Maybe.  But realize that there is a fundamental difference between VNC and RDP even on Windows.
VNC has always emulated the existing console no matter who is logged in to that console.  If multiple people connect via VNC to the same computer, they all see the same screen and are fighting over the mouse and keyboard.  Also, If Administrator happens to be logged in at the real console of the computer, anyone using VNC to connect is operating as Administrator.
RDP is a part of Windows Terminal Services which was designed to allow multiple users to connect to a server as themselves, simultaneously.  If Bob and Jane both log in to the same Server, they get independent screens with only their own keyboard and mouse controlling things.  If Bob is logged in to the Server on the console, and then logs in through RDP from his desk he does not see the apps he had running on the Server console.
If some creative programmer can figure out how to redirect all your X11 clients(apps) to the new X11 server(console/terminal) that Xrdp creates when you log in with XorgXrdp then you can get the functionality you are looking for without breaking the RDP design premise.  Since X11 was designed for actual graphics terminals connected to a mainframe, it might be possible.

**Comment by zilexa** [comment]
Thanks explaining. To me it's sad this is not properly documented and its very hard to find quality info and correct info. 

but I switched to Manjaro Gnome last year and it runs more stable (then Ubuntu) with built in RDP support for local desktop sharing :) no need to mess around.

**Comment by RavenWing71** [comment]
Glad it helped.
Documentation is the sad victim of Open Source.  Everybody wants to code, but so few want to document what they've done.  Not that I'm any better.  The advantage of paid projects is that they can afford to hire someone to write documentation.
As to VNC vs RDP, I've been in the industry long enough to have seen them both born, so I read the documentation back when they believed in it.  These days they tell you to google it but use terms that are so generic you can't find squat.  When you do manage to get your search terms right you can't trust half of what you find......
If you have the ability to mark this Issue as addressed, you probably should.

**Comment by matt335672** [comment]
@zilexa - just to add that if you just want to access your existing desktop, the GNOME RDP service that @RavenWing71 mentions above is installed as part of Ubuntu 22.04. If that's all you want to do, it's probably a better way for you to go.

**Comment by zilexa** [comment]
Yes, but I already switched to Manjaro. 
On Manjaro was already released with a Gnome version that included GNOME RDP last year. It just didn't had the UI to create credentials but did have perfect documentation to handle that via command line.

Much, much better documentation (Arch wiki!) and a much better out of the box experience, also better btrfs support fully built in (auto snapshots when updating, subvolume layout handled via the installer etc). So many reasons. 
Yes, there is much more written about Ubuntu but most of it is crap, out dated or not based on best practices. 

A bit offtopic, but thanks to Manjaro I've already been enjoying Gnome RDP service for a while now :)

**Comment by matt335672** [comment]
Great - glad you found something that meets your use case.
